# Image metadata and config.
# Ideally, the Node.js version should match what we use on CI.
FROM Node:22.15-bullseye


# Switch to `root`.
USER root


# Configure `Node.js`/`npm`.
RUN npm config --global set user root
